- name: template snic file server
  template:
    src: roles/software-repository/files/siebel-{{target_platform}}-update.rsp.j2
    dest: /tmp/siebel-{{target_platform}}-update.rsp

- name: check if we ran before server siebel UPDATE
  stat:
    path: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_update_version }}/Siebel_Install_Image/products.txt"
  register: server_install_image

- name: run snic.sh server
  command: ./snic.sh -silent -responseFile /tmp/siebel-{{target_platform}}-update.rsp
  args:
    chdir: "{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_update_version }}/unarchive"
  when:
    server_install_image.stat.exists == false
  environment:
    JAVA_HOME: "{{java_home}}"
    LANG: "C"
