---
# tasks file for siebel server

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/ses/oraInventory/"

- name: create siebel ses oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ses/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ses/oraInventory
       inst_group=siebel

- name: template install ses response file
  become: true
  become_user: siebel
  become_method: sudo
  template:
    src: roles/siebel-server/files/siebel-{{siebel_version}}-install-ses.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ses.rsp

- name: install ses
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ses.rsp -jreloc {{java_home}} -invPtrLoc {{siebel_base_path}}/ses/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: sudo
  args:
    chdir: "/mnt{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{ siebel_version }}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ses/siebsrvr"

#- name: check existing siebel database
#  shell : "source /home/siebel/.bash_profile && echo 'select name from siebel.s_repository;' | sqlplus sadmin/#BEstr0ng_#1@siebeldb"
#  become: true
#  become_user: siebel
#  become_method: sudo
#  args:
#    executable: "/usr/bin/bash"
#  register: siebel_database_exists
#
#- name: create siebel database
#  become: true
#  become_user: siebel
#  become_method: sudo
#  include: create-siebel-database.yml
#  when: siebel_database_exists.stdout.find("Siebel Repository") == -1

###############
- name: Install Tomcat init script
  copy:
    src: roles/siebel-server/files/ses-tomcat-initscript.sh
    dest: /etc/init.d/ses-tomcat
    mode: 0755

- name: Start Tomcat
  systemd:
    name: ses-tomcat
    state: started
    enabled: yes
    daemon_reload: yes

- name: wait for tomcat to start
  wait_for:
    port: 8102
    delay: 10
    state: started
