---
# tasks file for siebel application interface

#TODO install Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files 8

- name: create siebel_base
  file:
    path: "{{item}}"
    state: directory
    mode: 0775
    owner: siebel
    group: sse_role
  with_items:
    - "{{siebel_base_path}}"
    - "{{siebel_base_path}}/ai/oraInventory"

- name: create siebel ai oraInventory
  blockinfile:
    path: "{{siebel_base_path}}/ai/oraInventory/oraInst.loc"
    create: yes
    mode: 0775
    owner: siebel
    group: sse_role
    block: |
       inventory_loc={{siebel_base_path}}/ai/oraInventory
       inst_group=siebel

- name: template install appinterface response file
  become: true
  become_user: siebel
  become_method: sudo
  template:
    src: roles/siebel-ai/files/siebel-{{siebel_version}}-install-ai.rsp.j2
    dest: /tmp/siebel-{{siebel_version}}-install-ai.rsp

- name: install appinterface
  shell : "source /home/siebel/.bash_profile && ./runInstaller -silent -waitforcompletion -responseFile /tmp/siebel-{{siebel_version}}-install-ai.rsp -jreloc {{java_home}} -invPtrLoc {{siebel_base_path}}/ai/oraInventory/oraInst.loc"
  become: true
  become_user: siebel
  become_method: sudo
  args:
    chdir: "/mnt{{ software_repository_path }}/siebel-{{target_platform}}-{{ siebel_version }}/Siebel_Install_Image/{{siebel_version}}/{{target_platform}}/Server/Siebel_Enterprise_Server/Disk1/install"
    executable: "/usr/bin/bash"
    creates: "{{siebel_base_path}}/ai/applicationcontainer"

- name: Install Tomcat init script
  copy:
    src: roles/siebel-ai/files/ai-tomcat-initscript.sh
    dest: /etc/init.d/ai-tomcat
    mode: 0755

- name: Start Tomcat
  systemd:
    name: ai-tomcat
    state: started
    enabled: yes

- name: wait for tomcat to start
  wait_for:
    port: 8082
    delay: 10
    state: started
